### PR TITLE
minor formatting correction to bullet list

### PR DESCRIPTION
**Pull request by eddelbuettel**

### CODE REVIEW

**Comment by richfitz** [comment]
Thanks Dirk.  Just to be difficult (and because I've never really enjoyed writing knitr/sweave files) the .Rmd is generated from source files in the vignettes/src directory.  Will fix the README naming thing, too :)

**Comment by eddelbuettel** [comment]
Interesting.  I saw `src/` but didn't look there and then (while on commuter train).  What does that buy you, or are you just trying to be difficult?  ;-)

**Comment by richfitz** [comment]
It buys me a much faster way of writing docs than I can personally do it in knitr (I probably need to just get emacs configured better but that's a rabbit hole I try to stay away from).

More fundamentally it means my literate docs are all `source`-able; the actual script - https://github.com/richfitz/RcppR6/blob/master/vignettes/src/introduction.R - just looks like a over-commented R script and is compiled into Rmd by [sowsear](https://github.com/richfitz/sowsear).  There's a version of this that has been incorporated into knitr.

And then *having* that set of conventions means that I tend to comment analysis scripts in the same way so that everything can be converted R -> Rmd -> md later on.  See [here](https://github.com/traitecoevo/plant_paper/wiki) for a recently submitted version, which happens to a bunch of RcppR6 code.

**Comment by eddelbuettel** [comment]
I just added two or three lines to `~/.emacs` once to enable markdown and polymode.  And edit in emacs.

Simple enough for me, but you seem to require three additional layers :)

**Pull request merged**
